Analyze the content in current editor when its saved
microsoft/sarifer pull request #5
Opened 2022-11-16 21:49 UTC by yongyan-gh

# Description

Current extension starts background analysis every 3 seconds after users stop typing in the editor. 

It slows down the VS a bit, and we decide to only analyze the content when user saves.

2022-11-16 22:42 UTC, EasyRhinoMSFT commented on src/Sarif.Sarifer.Core/BackgroundAnalysisTextViewCreationListener.cs
> +        // private TextEditIdleAssistant inputAssistant;
>// private TextEditIdleAssistant inputAssistant; [](http://example.com/codeflow?start=8&length=48)

Is this needed?

2022-11-16 23:42 UTC, EasyRhinoMSFT requested changes
:clock1:

2022-11-17 00:07 UTC, yongyan-gh commented on src/Sarif.Sarifer.Core/BackgroundAnalysisTextViewCreationListener.cs
> +        // private TextEditIdleAssistant inputAssistant;
yes these are code to start analysis when user stop typing. commented them just in case we may want them back in future. what do you think?

2022-11-17 00:09 UTC, EasyRhinoMSFT commented on src/Sarif.Sarifer.Core/BackgroundAnalysisTextViewCreationListener.cs
> +        // private TextEditIdleAssistant inputAssistant;
Let's remove them, we can always get the code back from history.

2022-11-17 00:13 UTC, EasyRhinoMSFT approved these changes
:shipit:

2022-11-17 01:00 UTC, merged